<?php

/**
 * @file
 * This is the main module file for services_login_role.
 * 
 * @author Edxxu <jin.xu@insready.com>
 */

/**
 * Implementation of hook_services_resources_alter().
 */
function services_login_role_services_resources_alter(&$resources, &$endpoint) {
	$resources['user']['actions']['login']['file']['module'] = 'services_login_role';
	$resources['user']['actions']['login']['file']['name'] = 'resources/services_login_role.resources';
	$resources['user']['actions']['login']['callback'] = '_services_login_role_user_login';
}


/**
 * Implementation of hook_menu()
 */
function services_login_role_menu() {
	$items['admin/services/login-roles'] = array(
		'title' => t('设置允许登陆的角色'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array('services_login_role_setting_form'),
		'access arguments' => array('administer site configuration'),
		'file' => 'includes/services_login_role.admin.inc',
	);
	
	return $items;
}